# Generated by Django 4.2.10 on 2024-02-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_post_movie_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='movie_user',
        ),
    ]
