# Generated by Django 4.2.10 on 2024-02-21 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_remove_reviewrating_movie_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='created_at',
        ),
    ]
